### ISSUE TITLE
Implement cascade and orphanRemoval

### ISSUE THREAD

**Issue by bigfoot90** [ElectricMaxxx/DoctrineOrmPhpcrAdapterBundle#12]
It would be awesome to have support for `cascade` and `orphanRemoval` like in ORM.

[Cascade](http://doctrine-orm.readthedocs.org/en/latest/reference/working-with-associations.html#transitive-persistence-cascade-operations)
[Orphan Removal](http://doctrine-orm.readthedocs.org/en/latest/reference/working-with-associations.html#orphan-removal)

**Comment by bigfoot90** [comment]
@ElectricMaxxx ping

**Comment by ElectricMaxxx** [comment]
Yea that's the reason i created https://github.com/ElectricMaxxx/DoctrineOrmOdmAdapter/issues/5 cause its a task for the library. Atm that moment i thought that the refactoring of doctrines UoW would move on faster to get influences for organizing the Entity mapping in it 

But you are right would be a work together with https://github.com/ElectricMaxxx/DoctrineOrmOdmAdapter/issues/26 to get a better usage.
